using System.Collections.Generic;

namespace PolishSpeechLibrary.Model
{
    public class OrthographicAlphabet : Alphabet
    {
        private readonly IList<Letter> letters;

        public override AlphabetName Name => AlphabetName.Orthographic;
        public override IList<Letter> Letters => letters;

        public OrthographicAlphabet()
        {
            letters = GetAllLetters();
        }

        private IList<Letter> GetAllLetters()
        {
            return new List<Letter>()
            {
                new Letter(" ", null, null, false, true),
                new Letter("a", null, null, false, false),
                new Letter("ą", null, null, false, false),
                new Letter("b", null, null, false, false),
                new Letter("c", null, null, false, false),
                new Letter("ć", null, null, false, false),
                new Letter("d", null, null, false, false),
                new Letter("e", null, null, false, false),
                new Letter("ę", null, null, false, false),
                new Letter("f", null, null, false, false),
                new Letter("g", null, null, false, false),
                new Letter("h", null, null, false, false),
                new Letter("i", null, null, false, false),
                new Letter("j", null, null, false, false),
                new Letter("k", null, null, false, false),
                new Letter("l", null, null, false, false),
                new Letter("ł", null, null, false, false),
                new Letter("m", null, null, false, false),
                new Letter("n", null, null, false, false),
                new Letter("ń", null, null, false, false),
                new Letter("o", null, null, false, false),
                new Letter("ó", null, null, false, false),
                new Letter("p", null, null, false, false),
                new Letter("q", null, null, false, false),
                new Letter("r", null, null, false, false),
                new Letter("s", null, null, false, false),
                new Letter("ś", null, null, false, false),
                new Letter("t", null, null, false, false),
                new Letter("u", null, null, false, false),
                new Letter("v", null, null, false, false),
                new Letter("w", null, null, false, false),
                new Letter("x", null, null, false, false),
                new Letter("y", null, null, false, false),
                new Letter("z", null, null, false, false),
                new Letter("ź", null, null, false, false),
                new Letter("ż", null, null, false, false),
                new Letter("A", null, null, false, false),
                new Letter("Ą", null, null, false, false),
                new Letter("B", null, null, false, false),
                new Letter("C", null, null, false, false),
                new Letter("Ć", null, null, false, false),
                new Letter("D", null, null, false, false),
                new Letter("E", null, null, false, false),
                new Letter("Ę", null, null, false, false),
                new Letter("F", null, null, false, false),
                new Letter("G", null, null, false, false),
                new Letter("H", null, null, false, false),
                new Letter("I", null, null, false, false),
                new Letter("J", null, null, false, false),
                new Letter("K", null, null, false, false),
                new Letter("L", null, null, false, false),
                new Letter("Ł", null, null, false, false),
                new Letter("M", null, null, false, false),
                new Letter("N", null, null, false, false),
                new Letter("Ń", null, null, false, false),
                new Letter("O", null, null, false, false),
                new Letter("Ó", null, null, false, false),
                new Letter("P", null, null, false, false),
                new Letter("Q", null, null, false, false),
                new Letter("R", null, null, false, false),
                new Letter("S", null, null, false, false),
                new Letter("Ś", null, null, false, false),
                new Letter("T", null, null, false, false),
                new Letter("U", null, null, false, false),
                new Letter("V", null, null, false, false),
                new Letter("W", null, null, false, false),
                new Letter("X", null, null, false, false),
                new Letter("Y", null, null, false, false),
                new Letter("Z", null, null, false, false),
                new Letter("Ź", null, null, false, false),
                new Letter("Ż", null, null, false, false),
                new Letter(".", null, null, false, false),
                new Letter("!", null, null, false, false),
                new Letter("?", null, null, false, false),
                new Letter(",", null, null, false, false),
                new Letter(";", null, null, false, false),
                new Letter(":", null, null, false, false),
                new Letter("...", null, null, false, false),
                new Letter("(", null, null, false, false),
                new Letter(")", null, null, false, false),
                new Letter("#", null, null, false, false),
                new Letter("/", null, null, false, false),

                //new Letter(71, "!", null, null, false, false),
                //new Letter(72, "@", null, null, false, false),
                //new Letter(73, "#", null, null, false, false),
                //new Letter(74, "$", null, null, false, false),
                //new Letter(75, "%", null, null, false, false),
                //new Letter(76, "%", null, null, false, false),
                //new Letter(77, "(", null, null, false, false),
                //new Letter(78, ")", null, null, false, false),
                //new Letter(79, "-", null, null, false, false),
                //new Letter(80, "+", null, null, false, false),
                //new Letter(81, "=", null, null, false, false),
                //new Letter(82, "{", null, null, false, false),
                //new Letter(83, "}", null, null, false, false),
                //new Letter(84, "[", null, null, false, false),
                //new Letter(85, "]", null, null, false, false),
                //new Letter(86, ":", null, null, false, false),
                //new Letter(87, ";", null, null, false, false),
                //new Letter(88, "\"", null, null, false, false),
                //new Letter(89, "'", null, null, false, false),
                //new Letter(90, "?", null, null, false, false),
                //new Letter(91, "/", null, null, false, false),
                //new Letter(92, "\\", null, null, false, false),
                //new Letter(93, "<", null, null, false, false),
                //new Letter(94, ">", null, null, false, false),
                //new Letter(95, ",", null, null, false, false),
                //new Letter(96, ".", null, null, false, false),
        };
        }
    }
}